# Generated by Django 4.0.6 on 2022-08-10 13:23

from django.db import migrations, models
import django.db.models.deletion
import projects.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('weight', models.IntegerField(choices=[(5, 'Backend programming language'), (4, 'Backend Framework'), (3, 'Frontend Framework'), (2, 'Frontend - js, css, html'), (1, 'Tools - docker etc.')])),
            ],
            options={
                'ordering': ['-weight', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('thumbnail', models.ImageField(upload_to=projects.models.thumbnail_img_upload_path)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('source_code', models.CharField(blank=True, max_length=250, null=True)),
                ('demo', models.CharField(blank=True, max_length=250, null=True)),
                ('is_favourite', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account')),
                ('tags', models.ManyToManyField(related_name='projects', to='projects.tag')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
