# Generated by Django 4.0.6 on 2022-08-10 13:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=48)),
                ('description', models.TextField(blank=True, max_length=256, null=True)),
                ('link_github', models.CharField(blank=True, max_length=128, null=True)),
                ('link_linkedin', models.CharField(blank=True, max_length=128, null=True)),
                ('link_twitter', models.CharField(blank=True, max_length=128, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('sender_name', models.CharField(max_length=250)),
                ('sender_email', models.EmailField(max_length=250)),
                ('company', models.CharField(blank=True, max_length=250, null=True)),
                ('message', models.TextField(max_length=2000)),
                ('is_read', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.account')),
            ],
            options={
                'ordering': ['is_read', '-created'],
            },
        ),
    ]
